### ISSUE TITLE
Works on MacBookPro5,4

### ISSUE THREAD

**Issue by wilsonehusin** [aroman/elementary-on-a-mac#42]
I just want to point out that elementaryOS and the rEFInd works on a Mid-2009 Core2Duo MacBook Pro. In fact I am writing this using the machine. However, my OS X is 10.10 (Yosemite).

Also, I think it's worth adding [this](https://www.reddit.com/r/elementaryos/comments/38e5aq/elementaryos_on_macbook_pro/crvsrt3/) (copying color calibration settings) to make your display in elementaryOS looks as good as OS X / macOS because it helped my eyes a lot.

**Comment by aroman** [comment]
Thanks for the issue!

To be honest, I'm not sure why the line about "must not be core2duo" is there. I think it's because our guide is assuming you're using a CoreStorage partition (i.e. you have FileVault2 enabled in 10.7+ or are using 10.11+), and because of EFI stub loading. Certainly rEFInd can work on older macs — did you follow the steps of the guide exactly?

Would be totally open to a PR about the color settings :)

**Comment by wilsonehusin** [comment]
Well I did not follow the tutorial completely tbh :smile:. I had elementaryOS previously installed with GRUB. What happened to my Mac before installing rEFInd (which I found out from this repo) is that it will automatically go to GRUB where elementaryOS is the only option. When I hold `option` upon boot, then it will show both Macintosh HD and Recovery. After rEFInd, now it shows OS X, elementaryOS, and GRUB in Ubuntu logo :sweat_smile:

Anyway, I will try to do the PR tomorrow (EDT).
